[auto_update]
name = "自动更新工具"
date = "2025-04-21 21:56:14"
filelist = ["uma-autoupdate.exe"]
sha1 = "c4697d93369e7cddd25fc6d875b27aa1d45d96dd"
index = 6
install_path = "."
ver = "0.1.4"

[ura_data]
name = "小黑板数据"
date = "2025-11-28 18:05:20"
filelist = ["events.br", "events_female.br", "events_male.br", "factor_ids.br", "names.br", "skill_data.br", "skill_upgrade_speciality.br", "talent_skill_sets.br"]
install_path = "%localappdata%/UmamusumeResponseAnalyzer"
index = 3
sha1 = "406a8e942e38f812d3155bc6d0b261bf3778ee14"

[ai_data]
name = "AI数据"
date = "2025-11-28 18:23:54.616491"
filelist = [
	"umaDB.json",
    "cardDB.json",
    "text_data_dict.json"  
]
install_path = "db"
index = 2
sha1 = "f4c6ab8e22ed8e3d845b2b2c6fc0dbf73b6917b0"
