[auto_update]
name = "自动更新工具"
date = "2025-04-21 21:56:14"
filelist = ["uma-autoupdate.exe"]
sha1 = "c4697d93369e7cddd25fc6d875b27aa1d45d96dd"
index = 6
install_path = "."
ver = "0.1.4"

[ura_data]
name = "小黑板数据"
date = "2025-12-26 21:21:52.207887"
filelist = ["events.br", "events_female.br", "events_male.br", "factor_ids.br", "names.br", "skill_data.br", "skill_upgrade_speciality.br", "talent_skill_sets.br", "succession_relation.br", "wins_saddle.br"]
install_path = "%localappdata%/UmamusumeResponseAnalyzer"
index = 3
sha1 = "54843baa23e17bfe0a9cc3f7fcd2f33a504855b5"

[ai_data]
name = "AI数据"
date = "2026-01-08 15:53:33.195358"
filelist = [
	"umaDB.json",
    "cardDB.json",
    "text_data_dict.json"  
]
install_path = "gamedata"
index = 2
sha1 = "f0230928cae41f0af96ff0d19f634a84a54ffd73"
