[auto_update]
name = "自动更新工具"
date = "2025-04-21 21:56:14"
filelist = ["uma-autoupdate.exe"]
sha1 = "c4697d93369e7cddd25fc6d875b27aa1d45d96dd"
index = 6
install_path = "."
ver = "0.1.4"

[ura_data]
name = "小黑板数据"
date = "2025-11-11 11:39:01.186316"
filelist = ["events.br", "factor_ids.br", "names.br", "skill_data.br", "skill_upgrade_speciality.br", "success_events.br", "talent_skill_sets.br"]
install_path = "%localappdata%/UmamusumeResponseAnalyzer"
index = 3
sha1 = "2b1b9f470d713821f3213e6c559255bba2af171b"

[ai_data]
name = "AI数据"
date = "2025-11-11 11:28:00.144653"
filelist = [
	"umaDB.json",
    "cardDB.json",
    "text_data_dict.json"  
]
install_path = "db"
index = 2
sha1 = "1aef61d75d6cb9c2dfebc473b67cabc94977c6df"
