[auto_update]
name = "自动更新工具"
date = "2026-01-27 19:22:53.799410"
filelist = ["uma-autoupdate.exe"]
sha1 = "5afb01ecd1b048130f87a2ccc47156799f8a001c"
index = 6
install_path = "."
ver = "0.2.0"

[ura_data]
name = "小黑板数据"
date = "2026-02-15 20:49:04"
filelist = ["events.br", "events_female.br", "events_male.br", "factor_ids.br", "names.br", "skill_data.br", "skill_upgrade_speciality.br", "talent_skill_sets.br", "succession_relation.br", "wins_saddle.br"]
install_path = "%uraroot%/"
index = 3
sha1 = "4624ee508e00cafcad4ca4985e3741a8ada0b295"

[ai_data]
name = "AI数据"
date = "2026-02-15 20:42:28.505999"
filelist = [
	"umaDB.json",
    "cardDB.json",
    "text_data_dict.json"  
]
install_path = "gamedata"
index = 2
sha1 = "fd19adc9cc748bb03d77437c411053fff227bf1c"
