[auto_update]
name = "自动更新工具"
date = "2025-04-21 21:56:14"
filelist = ["uma-autoupdate.exe"]
sha1 = "c4697d93369e7cddd25fc6d875b27aa1d45d96dd"
index = 6
install_path = "."
ver = "0.1.4"

[ura_data]
name = "小黑板数据"
date = "2025-10-29 22:17:52.009296"
filelist = ["events.br", "factor_ids.br", "names.br", "skill_data.br", "skill_upgrade_speciality.br", "success_events.br", "talent_skill_sets.br"]
install_path = "%localappdata%/UmamusumeResponseAnalyzer"
index = 3
sha1 = "85f3a742e95ae2ef96699356ed2ecb7e3ad33333"

[ai_data]
name = "AI数据"
date = "2025-10-29 22:31:16.374575"
filelist = [
	"umaDB.json",
    "cardDB.json",
    "text_data_dict.json"  
]
install_path = "db"
index = 2
sha1 = "20ceb2204be540f1c4fcf562310337a0c576a8eb"
